### ISSUE TITLE
Problem when installing as a global

### ISSUE THREAD

**Issue by joakimbeng** [joakimbeng/unistyle#2]
Running `npm install -g unistyle` and then `unistyle folder` results in:

```
/usr/local/lib/node_modules/unistyle/src/index.js:1
(function (exports, require, module, __filename, __dirname) { import {resolve} from 'path';
                                                              ^^^^^^

SyntaxError: Unexpected reserved word
```

A fix is on its way...

**Comment by queckezz** [comment]
I think, this fix actually breaks local installation because it accesses `node_modules` which it can't since you did ignore it.

I would suggest removing the `babel/register` completely and rely on a npm `prepublish` step:

``` json
{
  "main": "build/index.js",
  "scripts": {
    "prepublish": "babel -o build/index.js src/index.js"
  }
}
```

then just let the user choose what preprocessor they use:

``` bash
babel src/index.js | unistyle -o dist/app.css
```

**Comment by queckezz** [comment]
See https://github.com/joakimbeng/unistyle/pull/3
