### ISSUE TITLE
@font-faces!

### ISSUE THREAD

**Issue by kalimantos** [joakimbeng/unistyle#9]
Hi guys!
how to define multiple @font-faces? As now it's only possible declare once, then the others overwrites the first one.

Ciao

**Comment by joakimbeng** [comment]
I'm on it!

Soon you will be able to declare those as an array:

``` javascript
export default {
  '@font-face': [
    {fontFamily: 'MyFont', src: [...]},
    {fontFamily: 'OtherFont', src: [...]}
  ]
};
```
